---
title: "Datenschutz"
---


Verantwortlicher für die Erhebung, Verarbeitung und Nutzung Ihrer personenbezogenen Daten im Sinne von Art. 4 Nr. 7 DSGVO ist

	Johannes-Gutenberg Universität
    Sarrstr. 21
    55122 Mainz
	Germany

___
### Betroffenenrechte: Rechte auf Auskunft, Berichtigung, Sperre, Löschung und Widerspruch
Sie haben das Recht, auf Antrag unentgeltlich eine Auskunft über die bei uns gespeicherten personenbezogenen Daten anzufordern und/oder eine Berichtigung, Sperrung oder Löschung zu verlangen. Eine Sperrung oder Löschung kann nicht erfolgen, wenn gesetzliche Regelungen dem entgegenstehen.

Bitte kontaktieren Sie unseren Datenschutzbeauftragten unter: datenschutz@uni-mainz.de

___
### Datenvermeidung und Datensparsamkeit
Wir speichern gemäß den Grundsätzen der Datenvermeidung und Datensparsamkeit personenbezogene Daten nur so lange, wie dies erforderlich ist oder vom Gesetzgeber vorgeschrieben wird.
Erfassung allgemeiner Informationen

Informationen zu einem Zugriff auf unsere Website werden durch unseren Provider automatisiert erfasst und in Form von Logfiles gespeichert. Die Logfiles sind von allgemeiner Natur und erlauben keine Rückschlüsse auf Ihre Person. Die Logfiles werden von uns nicht archiviert.

Sofern Logfiles erstellt werden, können unter anderem folgende Datenarten erfasst werden:

    Browsertyp und Browserversion
    Verwendetes Betriebssystem
    Besuchte Seiten und Inhalte
    Übertragene Datenmengen
    Verweisende Seite (Referrer URL)
    Datum und Uhrzeit Ihres Zugriffs
    anonymisierte IP-Adresse
___
### Cookies
Diese Website verwendet keine Cookies.
